"""add unaccented text

Revision ID: cc121b0db43c
Revises: 4d00c857ab53
Create Date: 2022-07-12 09:37:58.242068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc121b0db43c'
down_revision = '4d00c857ab53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('unaccented_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'unaccented_text')
    # ### end Alembic commands ###
